apiVersion: v1
kind: Service
metadata:
  name: k8s-redis-svc
  namespace: devops
spec:
  selector:
    app: k8s-redis-deployment
  ports:
    - protocol: TCP
      port: 6380
      targetPort: 6379
  type: NodePort
  