apiVersion: v1
kind: Service
metadata:
  name: k8s-webook-svc
  namespace: devops
spec:
  selector:
    app: k8s-webook-svc
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
  type: NodePort
  