apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: devops
  name: k8s-mysql-dt
  labels:
    app: k8s-mysql-dt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-mysql-dt
  template:
    metadata:
      name: k8s-mysql-dt
      labels:
        app: k8s-mysql-dt
    spec:
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: k8s-mysql-storage
      containers:
        - name: k8s-mysql-dt
          image: mysql:8.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: xayy@dev.123
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-storage
      restartPolicy: Always