apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8s-mysql-pv
spec:
  storageClassName: webook-mysql-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /raid/devops/data