apiVersion: v1
kind: Service
metadata:
  name: k8s-mysql-svc
  namespace: devops
spec:
  selector:
    app: k8s-mysql-dt
  ports:
    - protocol: TCP
      port: 3308
      targetPort: 3306
      nodePort: 32539
  type: NodePort
  