apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: devops
  name: k8s-mysql-storage
spec:
  storageClassName: webook-mysql-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi