version: '3.0'
services:
  mysql8:
    image: mysql:8.1.0
    ports:
      - "3306:3306"
    command:
      - --default-authentication-plugin=mysql_native_password
    volumes:
      - ./script/mysql/:/docker-entrypoint-initdb.d/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
  redis:
    image: redis:latest
    ports:
      - "6379:6379"